### ISSUE TITLE
how does this work?

### ISSUE THREAD

**Issue by Battler624** [lichie567/LMeter#1]
I installed and its working but it says not connected to the wen socket

**Comment by Battler624** [comment]
My bad, didn't realise I need a ws: (was using straight "localhost:10501"

Fixed with the new update :)

**Comment by ZXSwire3** [comment]
I'm kind of new to using ACT, I found the setting to enable the web server, but I'm having a hard time figuring out how to connect it. I was able to able to connect the the webserver through my browser, but I tried doing `ws://localhost:80` but it would just say that the connection failed while saying `127.0.0.1 - / - Length: 1064` in ACT. Am I missing something?

**Comment by Battler624** [comment]
> I'm kind of new to using ACT, I found the setting to enable the web server, but I'm having a hard time figuring out how to connect it. I was able to able to connect the the webserver through my browser, but I tried doing `ws://localhost:80` but it would just say that the connection failed while saying `127.0.0.1 - / - Length: 1064` in ACT. Am I missing something?


Yea LMeter doesn't support that webserver it requires the one provided by the overlay plugin
