### ISSUE TITLE
More visibility options

### ISSUE THREAD

**Issue by rechington** [lichie567/LMeter#11]
1. Hide in PvP
  Seems useless in PvP (mostly Frontline) as it's such a mess and not everyone is always in range to accurately track dps.
2. Hide in levequests
  Noticed that during miner and botanist levequests the overlay appears is if in a duty
3. Force show in FATEs

**Comment by zajrik** [comment]
What I'd like to see is a configurable hotkey for toggling display/hide. That's what I have set up for the ACT overlay plugin. I'm a total whore for topping DPS meters, but sometimes I want to focus on the fight and not be tempted to stare at my numbers, so being able to hide/show it in between GCDs for a quick peek at my position is ideal.

**Comment by lichie567** [comment]
Much better visibility options have been added in 0.4.0.0
