### ISSUE TITLE
[Feature Request] Windowed display

### ISSUE THREAD

**Issue by pigsflew** [lichie567/LMeter#23]
I'd love to be able to set the meter UI to in combat only, and then be able to call it up within a window using `/lm` (perhaps the configuration should be `/lmcfg`.

In my imagination, the window would also be able to change the sort and have a checkbox for Party at top vs mixed into the sort order, and maybe have tabs to order/show meters by HPS and Enmity, and potentially effective healing?

**Comment by lichie567** [comment]
This is possible with the `/lm toggle` command.
