### ISSUE TITLE
[Feature request] Show in combat or in duty

### ISSUE THREAD

**Issue by vpcn2019** [lichie567/LMeter#38]
Could you please add an option to show the meter either in combat or in duty (constantly)? As in, it appears only in combat out of duty and is always on when in duty.

**Comment by rootdarkarchon** [comment]
Please, I would love that as well. That way you could have overworld combat with lmeter and also have it visible in between pulls.

**Comment by HoloWise** [comment]
Double that

**Comment by lichie567** [comment]
This option has been added in 0.4.0.0
