### ISSUE TITLE
make it work on the latest version?

### ISSUE THREAD

**Issue by comprido** [lichie567/LMeter#48]
Hey man,
I want to thank you for the great job you did on LMeter.
Currently it does not work in the latest patch, do you plan to update it?

It would be great,
Cheers

**Comment by comprido** [comment]
Not happening :'(
I miss your plugin so much

**Comment by alexkleinubing** [comment]
> Not happening :'( I miss your plugin so much

@comprido try this repository https://github.com/Tischel/LMeter
