### ISSUE TITLE
fail to install

### ISSUE THREAD

**Issue by Aforgomon** [lichie567/LMeter#53]
When my Chinese server is loaded online, it prompts me to fail to install.,Local install is also installing failure.,The version is 3.0.0.,And I'm closing other plug-ins.,Load it separately.,Is there a problem with my operation?

**Comment by Shiyra69** [comment]
For me the same, it always shows ACTStatus: ConnectionFailed.

**Comment by lichie567** [comment]
Try version 3.0.1. Also, please upload your dalamud.log file when reporting issues.

**Comment by Aforgomon** [comment]
> Try version 3.0.1. Also, please upload your dalamud.log file when reporting issues.

Thank you very much, my problem solved
