### ISSUE TITLE
Center Text option

### ISSUE THREAD

**Issue by AnaRose356** [lichie567/LMeter#55]
There's left, right, and rank text options but could we get a center text option as well? Or purrhaps the option to add custom texts to the bars. I want it to be able to have both dps and hps included on a single bar and be able to color code them for instant snap viewing as a healer main.

The picture below shows what I'm trying to achieve with the rank text being colored green with the enchps moved to be centered in the bar but ideally I'd be able to have it near the dps numbers.
![image](https://github.com/lichie567/LMeter/assets/11483055/18e31ee9-17de-4d33-9fd2-deb3109978b1)

**Comment by lichie567** [comment]
I can probably add a center text option.

**Comment by Drake356** [comment]
![764167633234559016](https://github.com/lichie567/LMeter/assets/11483055/ba70c9ab-af0f-4eed-9f34-8e993349055d)

**Comment by lichie567** [comment]
This option has been added in 0.4.0.0

**Comment by AnaRose356** [comment]
You cooked with this update! Amazing work! Already spreading around all the news to my friends who don't use but maybe will use this plugin in the future, thank you! ♥
