### ISSUE TITLE
[Feature request] Damage breakdown

### ISSUE THREAD

**Issue by dlmw** [lichie567/LMeter#57]
It would be great to have a breakdown of the damage dealt. For example, when I click on my name in the LMeter window, I'd like to see how much damage each of my spells dealt (absolute and as a percentage) in that encounter. If that's implemented, maybe healers would like to see the breakdown of their healing spells, too.

I'm using IINACT, but I wonder if it's something that's supported by the parser or not.

**Comment by lichie567** [comment]
Unfortunately this is not possible, it is a limitation of ACT and the overlay plugin. LMeter can only show the data that ACT sends to it, and ACT does not have the ability to send that data.
