### ISSUE TITLE
Toggle chat command nonfunctional

### ISSUE THREAD

**Issue by petkorazzi** [lichie567/LMeter#59]
Attempting to toggle LMeter window visibility with the /lm toggle [integer] chat command does not work regardless of the status of the visibility options. This keeps one from being able to show/hide LMeter windows with a chat macro.

**Comment by raineszm** [comment]
I think `VisibilityConfig` just needs to be changed to `VisibilityConfig2` at https://github.com/lichie567/LMeter/blob/16275914dd4b9568f96639126edab7c87c0a9c72/LMeter/Config/MeterListConfig.cs#L35-L45

**Comment by lichie567** [comment]
This should be fixed with version 0.4.0.0
