### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Linoa235** [lichie567/LMeter#66]
There is a bug with version 4.0 it no longer displays the dps carried out it marks as before its remains at 0.0

**Comment by lichie567** [comment]
I am aware of this issue and am working on it now... I still don't know the cause because it is only affecting some people. Me and a few of my testers have been unable to recreate the issue. Hopefully I can fix it today.

**Comment by lichie567** [comment]
I've just pushed another update that should resolve this issue, please let me know if it works.

Sorry for the inconvenience!

**Comment by Linoa235** [comment]
> I've just pushed another update that should resolve this issue, please let me know if it works.
> 
> Sorry for the inconvenience!

No problem ^^ it happens, I thought I had broken something I deleted everything and reinstalled, but there was still the problem ^^

**Comment by Linoa235** [comment]
As soon as I have the update available on Dalamud I will tell you, if the problem is resolved

**Comment by Linoa235** [comment]
> I've just pushed another update that should resolve this issue, please let me know if it works.
> 
> Sorry for the inconvenience!

Problem solved, thank you for your speed ^^
