### ISSUE TITLE
LMeter failing to load. 

### ISSUE THREAD

**Issue by KorbenC** [lichie567/LMeter#72]
[dalamud_log.log](https://github.com/user-attachments/files/16380100/dalamud_log.log)

Launched game like normal but LMeter failed to load. Providing log

**Comment by comprido** [comment]
indeed, lmeter does not work in the latest version of the game :(
Can you please provide an update.

**Comment by lichie567** [comment]
Checked the log, this is not an issue with LMeter but an issue with Dalamud that should be fixed soon if it has not been fixed already. Restarting your game should work to resolve this error.
