### ISSUE TITLE
`Hide Tag Values if Zero` doesn't work with some tags

### ISSUE THREAD

**Issue by fakeleb** [lichie567/LMeter#80]
The `Hide Tag Values if Zero` option doesn't seem to work with a few tags, such as `[deaths]`, `[kills]` and  any `[***pct]`.

Example:
![example](https://github.com/user-attachments/assets/153d9173-a63c-4e01-865d-9519c4274fcd)

**Comment by lichie567** [comment]
This should be fixed in the latest update 0.4.1.3, please let me know if its not for you.
