### ISSUE TITLE
Disable automatic debug messages being displayed in chat

### ISSUE THREAD

**Issue by ChristallerPierre** [lichie567/LMeter#84]
Hey, can you please add any way to disable the automatic debug messages displayed in chat ?
I'd like LMeter to not display messages saying "end" in chat, after every fight.

I don't mind information messages displayed whenever the user inputs a command or manually interacts with LMeter's UI (for example to clear the log window) for relevant information. On the other hand, messages being displayed automatically pertain to the debug side of running a software in my opinion, meaning the user should be able to hide them if necessary.

**Comment by lichie567** [comment]
They are not debug messages. They happen because you enable the feature for LMeter to end the ACT encounter when leaving combat. The way to stop ACT from in game is to put that message into chat. ACT sees the chat message and stops the encounter.
