### ISSUE TITLE
Is it possible to display GCD active/idle time?

### ISSUE THREAD

**Issue by FreezyLemon** [lichie567/LMeter#85]
I don't think any of the existing tags track the GCD utilization (what FFlogs calls "Active %"). I am not sure if this information is simple to get from ACT, but it would be nice to have for casters.

**Comment by lichie567** [comment]
Such a metric doesn't exist in ACT. FFLogs calculates the active % from the raw log file. I don't think this feature really belongs in LMeter but there may be other plugins that already do this (I think NoClippy and XIVAlexander might do this already).
